# Generated by Django 3.1.3 on 2020-11-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201112_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章列表', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='blog_article',
        ),
        migrations.AlterModelTable(
            name='category',
            table='blog_category',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='blog_tags',
        ),
    ]
